name: MakUtils
version: '0.0'
main: org.makutils.makutils.Makutils
api-version: '1.21.5'
description: 'Nothing is impossible, the word itself says Im possible!'
#commands:
#  heal:
#    description: restore your health to max
#    usage: /<command>